### ISSUE TITLE
android 4.3上UIAlertView显示异常

### ISSUE THREAD

**Issue by TravellingBee** [AriesHoo/UIWidget#1]
4.3上UIAlertView，屏幕变暗，但是完全看不见Dialog

**Comment by AriesHoo** [comment]
你们项目还支持4.3啊。。我这边没有4.3的真机。。模拟器也创建不了。4.1和4.4都是正常的，再次确认下你的library是否为最新版本

**Comment by AriesHoo** [comment]
compile 'com.github.AriesHoo:UIWidget:2.0.2'
