### ISSUE TITLE
UIProgressDialog的圆形圈圈的颜色还是沿用原来的灰色最好，现在默认好像是绿色

### ISSUE THREAD

**Issue by hegelsu** [AriesHoo/UIWidget#10]

**Comment by AriesHoo** [comment]
UIProgressDialog默认颜色取系统colorAccent 控制与原始值保持一致，请使用https://jitpack.io/#AriesHoo/UIWidget/3.0.0-alpha4  版本尝试

**Comment by hegelsu** [comment]
刚试了一下，UIProgressDialogNormal的那个转圈圈的还是绿色的呢，我这这也没做过什么特殊的设置

**Comment by AriesHoo** [comment]
我试过在没设置colorAccent的情况下系统默认就说有点偏绿蓝的感觉，你可以同步试一试progressBar的颜色
