### ISSUE TITLE
RadiusTextView为不可点击状态时，代码中设置背景色无效

### ISSUE THREAD

**Issue by manburenshenglu** [AriesHoo/UIWidget#12]

**Comment by AriesHoo** [comment]
请注意不可点击是设置  setEnable 不是设置setClickable

**Comment by AriesHoo** [comment]
代码中设置所有属性完成后请调用init()方法。。还有就在提问题的时候附带下自己设置的代码。只描述问题，。懵的

**Comment by manburenshenglu** [comment]
<com.aries.ui.view.radius.RadiusTextView
            android:id="@+id/rtv_submit"
            android:layout_width="@dimen/dp_60"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:clickable="true"
            android:gravity="center"
            android:padding="@dimen/dp_5"
            android:text="取  消"
            android:textSize="@dimen/sp_12"
            app:rv_backgroundColor="@color/color_btn_press"
            app:rv_backgroundPressedColor="@color/color_btn_press"
            app:rv_radiusHalfHeightEnable="false"
            app:rv_strokePressedColor="@color/color_btn_press"
            app:rv_strokeWidth="1dp"
            app:rv_radius="@dimen/dp_6"
            app:rv_textColor="@color/white" />
然后代码中我是根据后台返回的状态来设置取消按钮是否可以点击，不可点击时，将取消按钮的背景色置灰，代码中调用setBackground无效

**Comment by AriesHoo** [comment]
xml设置 app:rv_backgroundDisabledColor  然后代码控制setEnable()即可。
