### ISSUE TITLE
Enable和rippleEnable冲突

### ISSUE THREAD

**Issue by zofnk** [AriesHoo/UIWidget#14]
![image](https://user-images.githubusercontent.com/17997544/44454601-7c5d5d00-a62e-11e8-98e5-d6011214d95e.png)
代码如上 , 同时设置 enable="false"  & rv_rippleEnable="ture"
在AS预览界面中没有问题 , 实际运行后TextView的背景色依然是可点击状态下的颜色 , 但点击后是没效果的 , 就背景色不对

**Comment by AriesHoo** [comment]
请使用最新的库，我一直在用，没有出现你说的情况

**Comment by AriesHoo** [comment]
抱歉，之前是我理解错误，3.2.6_beta2已修复
