### ISSUE TITLE
没有适配刘海

### ISSUE THREAD

**Issue by Goo-git** [AriesHoo/UIWidget#16]
没有适配Android P刘海

**Comment by AriesHoo** [comment]
能截图看看吗。全屏模式的我确实是没有适配也暂时没有计划适配。非全屏模式下应该不影响，我公司也有很多刘海屏的

**Comment by Goo-git** [comment]
我也没有真机，模拟器上运行的
![image](https://user-images.githubusercontent.com/12099702/48890082-c85caf80-ee72-11e8-864b-5694fa06a265.png)

**Comment by AriesHoo** [comment]
有这么高的刘海吗？

**Comment by AriesHoo** [comment]
我看实际的刘海都是在状态栏的位置的

**Comment by Goo-git** [comment]
实际刘海确实要小很多，可能是我有强迫症（哈哈），官方其实有解决方案的DisplayCutout

**Comment by AriesHoo** [comment]
这个我是知道的。后面加上就好。国内应该没有那种刘海超过状态栏的吧

**Comment by AriesHoo** [comment]
3.2.14版本已适配
