### ISSUE TITLE
建议RadiusCheckBox  rv_strokeWidth  分选择时的和默认

### ISSUE THREAD

**Issue by chenyang1900** [AriesHoo/UIWidget#18]
![image](https://user-images.githubusercontent.com/15828867/52609264-a2660a80-2eb7-11e9-9903-56c340d962c5.png)
如图上场景

**Comment by AriesHoo** [comment]
意思是选中和默认的粗细还有区分，是这个意思吗？我这个RadiusView的初衷就是尽可能解放shape文件,shape文件是否支持你的使用场景。如果支持我这边可以试一试，如果不支持，个人建议不用去折腾
