### ISSUE TITLE
UIAlertDialog 不显现分割线

### ISSUE THREAD

**Issue by HuChangyin** [AriesHoo/UIWidget#19]
3.2.7,3.2.8.0...UIAlertDialog IOS风格 ,两个按钮,不显示水平分割线..3.2.6正常

**Comment by AriesHoo** [comment]
1、是否在同一项目同一设备(手机)测试的效果，只是修改了版本产生的分割线不同
2、分割线默认设置0.5dp可能部分手机会显示不出通过设置dp_line_size 覆盖库里默认值
3、我这所有版本都可正常显示也没有升级去修改过这个默认值

**Comment by HuChangyin** [comment]
1, 是同一部手机,同一项目
2. 全是默认值 setDividerWidth(),同样无效 
3 .2个按钮不显示水平分割线,3个按钮正常显示
4. 3.2.7 ,3.2.8同样问题

**Comment by AriesHoo** [comment]
麻烦提供下，示例代码 。我这
setDividerWidth()是可行的

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/53539873-3d184780-3b4e-11e9-9f9c-6aecefb8b939.png)

**Comment by HuChangyin** [comment]
![screenshot_20190304-114519](https://user-images.githubusercontent.com/10334914/53709703-96e18000-3e74-11e9-819a-8a6cd2360e9d.jpg)

            new UIAlertDialog.DividerIOSBuilder(getActivity())
                    .setDividerWidth(20)
                    .setMessage("确定" + tvAgainSell.getText().toString() + "?")
                    .setNegativeButton("取消", null)
                    .setPositiveButton("确定", (dialog, which) -> changeSellStatus())
                    .setMinHeight(SizeUtils.dp2px(160))
//                    .setNeutralButton("测试" ,onAlertClick)
//                    .setNeutralButtonTextColorResource( R.color.colorAlertButton )
                    .create()
                    //  .setDimAmount(0.6f)
                    .show();

**Comment by HuChangyin** [comment]
是不是,我没有使用androidx的原因?

**Comment by AriesHoo** [comment]
你直接运行 demo也是一样的问题吗

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/53783727-c0220f00-3f4d-11e9-8d73-190f62b4215a.png)

这是用你代码效果

new UIAlertDialog.DividerIOSBuilder(mContext)
                        .setDividerWidth(20)
                        .setMessage("确定?")
                        .setNegativeButton("取消", null)
                        .setPositiveButton("确定", null)
                        .setMinHeight(SizeUtil.dp2px(160))
                        // .setNeutralButton("测试" ,onAlertClick)
                        // .setNeutralButtonTextColorResource( R.color.colorAlertButton )
                        .create()
                        // .setDimAmount(0.6f)
                        .show();

**Comment by AriesHoo** [comment]
你先试一试最新版本 3.2.9在你手机上是否运行正常？实在不行就使用3.2.6
