### ISSUE TITLE
TitleBarView和BottomNavigationView冲突

### ISSUE THREAD

**Issue by TanWenPing** [AriesHoo/UIWidget#2]
点击BottomNavigationView的item时,TitleBarView会顶到StatusBar上面去,导致页面内容挤压标题

**Comment by AriesHoo** [comment]
我这边试了下，没有出现点击item TitleBarView被挤压的情况呢。。。你是否可以提供一个demo，或者先试一试调用titleBar.setBottomEditTextControl()方法

**Comment by AriesHoo** [comment]
compile 'com.github.AriesHoo:UIWidget:2.0.2'
