### ISSUE TITLE
未引入androidx相关包，设置左右icon颜色造成闪退问题

### ISSUE THREAD

**Issue by AndMy** [AriesHoo/UIWidget#22]
我在layout_title_bar布局里，设置左边的图标，启动闪退，
![image](https://user-images.githubusercontent.com/7222340/55779642-902fd380-5ad8-11e9-96ca-5b7c0250c121.png)                        然后在代码里设置也闪退，
![image](https://user-images.githubusercontent.com/7222340/55779668-a2117680-5ad8-11e9-9fae-54fe3459cbfa.png)，这是什么问题；如果不设置左边的图片就没问题

**Comment by AriesHoo** [comment]
闪退有没有日志呢。这种应该是有闪退日志的

**Comment by AndMy** [comment]
关键是啥也没有，有的话我这边就解决了，找不到原因，跳转到那个activity就闪退了

**Comment by AriesHoo** [comment]
你可以参考下我demo设置的，有左右图片的，换其他图片资源是否也出问题？

**Comment by AndMy** [comment]
> 你可以参考下我demo设置的，有左右图片的，换其他图片资源是否也出问题？
我用的布局，就是你demo里的也不行
放入图片xml就不能预览了就像下面这样
![image](https://user-images.githubusercontent.com/7222340/55780216-0b45b980-5ada-11e9-8748-7c23a6531034.png)
![image](https://user-images.githubusercontent.com/7222340/55780227-126cc780-5ada-11e9-8d52-5a2ae5d0e0f8.png)  如果去掉图片就可以预览
![image](https://user-images.githubusercontent.com/7222340/55780275-2b757880-5ada-11e9-97be-414130792b05.png)
![image](https://user-images.githubusercontent.com/7222340/55780312-3b8d5800-5ada-11e9-997c-0c17c4e165c7.png)

**Comment by AriesHoo** [comment]
我猜测是那个图标drawable问题。可以传上来我这边看看？

**Comment by AndMy** [comment]
> 我猜测是那个图标drawable问题。可以传上来我这边看看？

你那边layout_title_bar的xml如果放入图片会看到预览效果吗？下面这个是图片
![hospital_sign](https://user-images.githubusercontent.com/7222340/55780951-b0ad5d00-5adb-11e9-9558-e579443c30a5.png)
这个图片在as里打开没问题，我在别的项目cope过来的，不应该是这个图片的问题

**Comment by AriesHoo** [comment]
去掉 title_leftTextDrawableTint 这个属性就可以直接预览，你给我的图标我这边运行显示是正常的。你把title_leftTextDrawableTint  属性去掉试一试？，你的手机Android 版本多少？
![image](https://user-images.githubusercontent.com/19605922/55781635-37af0500-5add-11e9-8e94-d535d133da15.png)

**Comment by AndMy** [comment]
去掉这个就好了，title_leftTextDrawableTint
android版本是6.0
华为手机MT7-TL00，系统版本号 EMUI系统4.0.1

**Comment by AriesHoo** [comment]
可能是设置图标颜色兼容性问题

**Comment by AndMy** [comment]
> 可能是设置图标颜色兼容性问题
好的谢谢了 title_rightTextDrawableTint这个也得去掉了吧

**Comment by AriesHoo** [comment]
按道理你的手机是6.0的不该出现drawable改颜色问题，我之前在模拟器4.4都试过的，你是用的Demo测试吗？

**Comment by AndMy** [comment]
> 可能是设置图标颜色兼容性问题
好的谢谢了 title_rightTextDrawableTint这个也得去掉了吧


> 按道理你的手机是6.0的不该出现drawable改颜色问题，我之前在模拟器4.4都试过的，你是用的Demo测试吗？
我应该知道什么问题了，你的类库用了androidx，我用的27，里面有个类找不到
![image](https://user-images.githubusercontent.com/7222340/55782407-ccfec900-5ade-11e9-8a35-5f3067c6023c.png)
![image](https://user-images.githubusercontent.com/7222340/55782422-d6883100-5ade-11e9-9ad2-a4912b1dab0d.png)
应该是这个问题
