### ISSUE TITLE
关于自定义action的问题

### ISSUE THREAD

**Issue by AndMy** [AriesHoo/UIWidget#24]
action自定义了，中间和右边，布局会显示不全
下面是自定义action布局
![image](https://user-images.githubusercontent.com/7222340/55788033-2c160b00-5aea-11e9-9954-586cceac1685.png)
代码设置
![image](https://user-images.githubusercontent.com/7222340/55788119-4ea82400-5aea-11e9-811d-975bc7a87343.png)
显示效果
![IMG_20190409_170705](https://user-images.githubusercontent.com/7222340/55788164-641d4e00-5aea-11e9-8a82-e2eff8000722.jpg)

这个是什么原因造成的

**Comment by AriesHoo** [comment]
还要设置LayoutParams 现在没有单独的api暴露出来，。后面会增加，可以通过 titleBar.getLinearLayout 获取 然后添加子布局

**Comment by AndMy** [comment]
老哥，什么时候发版，在线等。。。

**Comment by AriesHoo** [comment]
最近有点忙。后面会增加的。现在可以通过 titleBar.getLinearLayout 获取 然后添加子布局解决问题。实际都是通过一样的方式。未来添加api也是一样的套路

**Comment by AndMy** [comment]
类似这样搞？
![image](https://user-images.githubusercontent.com/7222340/55796999-ed8a4b80-5afd-11e9-8ae6-c48d8a09b321.png)

**Comment by AriesHoo** [comment]
你看下ViewGroup addView的重载方法呢，貌似不是你样的操作

**Comment by AriesHoo** [comment]
3.2.13版本已增加相关Api并且在TitleActionActivity里增加部分demo效果演示可供参考
