### ISSUE TITLE
TitleBarView 通过setImmersible动态设置mIsPlusStatusHeight属性

### ISSUE THREAD

**Issue by Vicent9920** [AriesHoo/UIWidget#27]
建议增加一个方法，可以动态设置```mIsPlusStatusHeight```属性，因为在```Fragment```使用的时候有些时候需要动态设置该属性来修改```TitleBarView```的上边距。虽然使用反射来也可以实现，但是始终不如原生开放来得方便。

**Comment by AriesHoo** [comment]
不太明白你的使用场景-可以仔细描述一下配合图片更好。setImmersible 有多个重载方法。里面有isPlusStatusBar参数设置
