### ISSUE TITLE
点击某个按钮有时 TitleBarView 会重绘,title会顶到状态栏去

### ISSUE THREAD

**Issue by TanWenPing** [AriesHoo/UIWidget#3]
点击某个按钮有时 TitleBarView 会重绘,title会顶到状态栏去

**Comment by AriesHoo** [comment]
再描述清楚些。能否提供Demo，TitleBarView本身就是一直在状态栏下边的，会延伸到状态栏下边

**Comment by TanWenPing** [comment]
![screenshot_20171109-163243_01](https://user-images.githubusercontent.com/9053147/32595675-b82c4660-c56b-11e7-9e7b-833f17663554.jpg)
![screenshot_20171109-163019_01](https://user-images.githubusercontent.com/9053147/32595599-73a3353a-c56b-11e7-90ea-4ad32ad57841.jpg)
  @AriesHoo 如图,开始是第一张图的样子,点击了一个按钮就变成第二张的样子了

**Comment by TanWenPing** [comment]
![screenshot_20171109-163243_01](https://user-images.githubusercontent.com/9053147/32595675-b82c4660-c56b-11e7-9e7b-833f17663554.jpg)
开始是这

**Comment by AriesHoo** [comment]
这个你确实要把你设置的Demo给我下，我才好分析，只需xml布局和activity不需要其它无关的逻辑

**Comment by TanWenPing** [comment]
项目代码不方便贴出. 点击按钮或者刷新列表时执行了TitleBarView类中的onLayout()和onMeasure()这两方法,然后标题就挤压上去了,6.0的系统没问题,8.0的系统有问题,也许是和系统版本有个也许和手机型号有关.
好像xml根布局使用ConstraintLayout和LinearLayout效果也不一样,使用ConstraintLayout时高度设置32dp就和标准高度一样了,而使用LinearLayout要设置56dip才和标准高度一样.
详细情况就这样

**Comment by TanWenPing** [comment]
经过进一步测试,有可能是因为xml文件中TitleBarView的父级是ConstraintLayout导致的,你可以试试.
下班了,周末愉快

**Comment by AriesHoo** [comment]
ok 了解了。。我这边研究下

**Comment by AriesHoo** [comment]
2.0.5版本修改父容器为ConstraintLayout高度测量不准BUG，点击某个Button TitleBarView变形问题没有发现，录屏中有ConstraintLayout界面效果在8.0模拟器录制如果还有问题调用setBottomEditControl方法看看
