### ISSUE TITLE
UIProgressDialog最新版只能使用androidx？

### ISSUE THREAD

**Issue by AndMy** [AriesHoo/UIWidget#30]
DragLayout这个类。。。。
![image](https://user-images.githubusercontent.com/7222340/58082047-d0f72e00-7be8-11e9-821d-f3436e285313.png)

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/58082209-1f0c3180-7be9-11e9-90b4-3dfcce4447c9.png)
最新版本肯定是只支持AndroidX的3.2.7是最后一个support编译的版本，Androidx是趋势早点切换早好

**Comment by AndMy** [comment]
好吧，涉及太多，迎来的问题很多。。。

**Comment by AriesHoo** [comment]
如果改动最小的话就将源码下载下来本地变更为support模式。要快捷些

**Comment by AndMy** [comment]
> 如果改动最小的话就将源码下载下来本地变更为support模式。要快捷些

我升级androidx了，但是有点问题，和你效果图不一致，
![image](https://user-images.githubusercontent.com/7222340/58149821-15410780-7c97-11e9-8912-fb9587bef21a.png)
下图是效果图，loading是白色的，文体是白色的
![image](https://user-images.githubusercontent.com/7222340/58149918-8e405f00-7c97-11e9-8d5d-9ed68b982476.png)
我知道可以通过设置属性来改变，可是你demo里没设置，是默认的，想问一下，我使用的最新版是不是没有加载到你的资源文件，aar进去，显示R文件找不到
![image](https://user-images.githubusercontent.com/7222340/58150011-d6f81800-7c97-11e9-80e1-96ca99ada58c.png)

**Comment by AriesHoo** [comment]
![image](https://user-images.githubusercontent.com/19605922/58150385-0ce9cc00-7c99-11e9-9e2b-73939acbeb21.png)
![image](https://user-images.githubusercontent.com/19605922/58150406-170bca80-7c99-11e9-8dc7-7551f52c2eea.png)
我默认拿的是colorAccent属性。你看下你设置的是什么颜色

**Comment by AndMy** [comment]
嗯嗯，我的是白色，那个R文件找不到，应该没事吧

**Comment by AriesHoo** [comment]
没事的。编译了的都会是那样的你可以看下其它三方库和Android SDK都是一样的效果

**Comment by AndMy** [comment]
好的谢谢了，谢谢你的库
