### ISSUE TITLE
打开一个弹窗,熄屏后再次开屏 分割线消失了 

### ISSUE THREAD

**Issue by a1265137718** [AriesHoo/UIWidget#31]
打开一个弹窗,熄屏后再次开屏 分割线消失了 
弹窗的样式为三个按钮的 消息和 底部三个按钮的默认的黑色分割线消失

**Comment by AriesHoo** [comment]
不清楚你说的啥情况，我试了下demo好像正常的。方便的话截图看看，能录屏最佳
