### ISSUE TITLE
加一个全屏的方法？StatusViewHelper这个或者StatusBarUtil这个里面

### ISSUE THREAD

**Issue by AndMy** [AriesHoo/UIWidget#33]
加一个全屏的方法？StatusViewHelper这个或者StatusBarUtil这个里面

**Comment by AriesHoo** [comment]
3.2.19版本StatusBarUtil增加setFullScreen、hideStatusBar方法、NavigationBarUtil增加hideNavigationBar方法

**Comment by AndMy** [comment]
setFullScreen全屏是 状态栏+底部导航栏都全屏？

**Comment by AriesHoo** [comment]
对的。setFullScreen 是状态栏导航栏同时有效

**Comment by AndMy** [comment]
好的，谢谢了
