### ISSUE TITLE
TitleBarView 横竖屏切换刘海屏适配问题

### ISSUE THREAD

**Issue by QinAndroid** [AriesHoo/UIWidget#35]
华为P20 刘海屏，竖屏显示正常，但是切换到横屏之后 会显示异常 我用demo试了 也一样存在异常

**Comment by AriesHoo** [comment]
这个我知道。建议强制竖屏尝试过ROM被改得很乱不好弄，就放弃了

**Comment by AriesHoo** [comment]
竖屏啥问题，发个截图看看

**Comment by QinAndroid** [comment]
![微信图片_20190815143427](https://user-images.githubusercontent.com/6628144/63077130-e1117600-bf69-11e9-9afa-1661fd1ee83d.jpg)

**Comment by QinAndroid** [comment]
横屏之后 左边就被遮挡了 竖屏是没问题的

**Comment by AriesHoo** [comment]
这个没有问题的，这个横屏需要自己去处理，通过 NotchUtil.getSafeInsetLeft()等属性，去处理，或者不使用刘海屏 StatusBarUtil.fitsNotchScreen();库哪里知道哪个View需要设置padding规避,还有建议手机应用尽量强制竖屏可能比较好，除非播放视频

**Comment by QinAndroid** [comment]
嗯，谢谢 ，提供的demo 中 有对这块的说明吗？

**Comment by AriesHoo** [comment]
木有，后面在demo主页添加相应说明
