### ISSUE TITLE
RadiusRelativeLayout滑动冲突

### ISSUE THREAD

**Issue by sceneren** [AriesHoo/UIWidget#41]
RadiusRelativeLayout 作为recyclerView的根布局,会与smartrefreshLayout产生滑动冲突

**Comment by sceneren** [comment]
我不确定是和SmartRefreshLayout冲突还是RecyclerView冲突

**Comment by AriesHoo** [comment]
提供下xml布局

**Comment by AriesHoo** [comment]
只需要大概层级即可

**Comment by sceneren** [comment]
![image](https://user-images.githubusercontent.com/6612998/94338037-cbea9000-0021-11eb-90d0-2acf2d2195fc.png)
如果用
RadiusRelativeLayout作为根布局就会出现冲突,加了一层就好了

**Comment by AriesHoo** [comment]
收到，你先这样解决，我看看啥问题
