### ISSUE TITLE
RadiusTextView 支持ripple点击效果？

### ISSUE THREAD

**Issue by AndMy** [AriesHoo/UIWidget#43]
RadiusTextView 支持ripple点击效果？

**Comment by AriesHoo** [comment]
支持,可关闭;可当作 Button使用

**Comment by AndMy** [comment]
我这样添加的，下面是图片
![图片](https://user-images.githubusercontent.com/7222340/99499361-bce5e580-29b3-11eb-93ce-1f04f954f5a7.png)
然后快速点击整个背景有变化，但是没有波纹效果，长按的话整个背景渐变
我看demo里面的RadiusFrameLayout，RadiusLinearLayout点击的话有一个白色的水波一圈一圈的

**Comment by AriesHoo** [comment]
这个是系统自带的效果，你看我demo。首页list 类似效果。如果没有就是系统支持程度问题，可以不用太纠结

**Comment by AndMy** [comment]
好的，那我关闭
