### ISSUE TITLE
TitleBarView添加一个自定义视图后，没有办法删除

### ISSUE THREAD

**Issue by leifengwl** [AriesHoo/UIWidget#44]
例如我在左边添加一个自定义视图后，切换到另外一个界面，似乎没办法动态删除它

**Comment by AriesHoo** [comment]
TitleBarView本质上是一个ViewGroup 左边也是一个ViewGroup 似乎是可以动态删除的

**Comment by AriesHoo** [comment]
titleBar.getLinearLayout(Gravity.LEFT)  获取左边Layout 删除已添加的view即可

**Comment by leifengwl** [comment]
谢谢，我现在尝试下

**Comment by leifengwl** [comment]
已经测试，确实可以实现，非常感谢
