### ISSUE TITLE
集成了TitleBarView, 使用正常, 但log有一句警告打印

### ISSUE THREAD

**Issue by rainie941217** [AriesHoo/UIWidget#5]
W/ResourceType: No known package when getting value for resource number 0xffffffff
网上搜索说是可能少了些东西,  虽然使用正常, 但还是有些疑问, 求解答..

**Comment by AriesHoo** [comment]
这是设置TextView的drawable属性资源时候我使用的try 避免因为设置资源id找不到造成奔溃
