### ISSUE TITLE
Android10上底部有间距，不填充

### ISSUE THREAD

**Issue by AndMy** [AriesHoo/UIWidget#50]
baseactivity里设置你demo里的那些方法的话
如下代码
![image](https://user-images.githubusercontent.com/7222340/112286223-104fa380-8cc6-11eb-8aee-c94ffb435b4f.png)

Android10上底部有间距，不能填充到底部
如下图

![bug1](https://user-images.githubusercontent.com/7222340/112286864-bbf8f380-8cc6-11eb-9b3e-f0df403f625f.png)

**Comment by AriesHoo** [comment]
setPlusNavigationViewEnable(false,false,false)试一试

**Comment by AndMy** [comment]
可以了，谢谢
