### ISSUE TITLE
有个奇怪的问题

### ISSUE THREAD

**Issue by hegelsu** [AriesHoo/UIWidget#7]
1. 我在海马玩模拟器里装上appdemo测试，发现uialertview点按钮过久才会有反映，但在我手机里又没事，不知道什么原因，平时开发都是在模拟器里搞，总以为有问题，但一想真机没事就算了，可我在这个模拟器里用其它的弹框组件也没出现这个问题啊，可有真机里还有按下的阴影效果，但在模拟器里就没有了任何效果
2. 另外问下弹出输入框的输入区域的背景颜色如何修改

**Comment by AriesHoo** [comment]
1、一般情况下我也是在模拟器(自带的非三方)上测试验证的，模拟器毕竟是模拟器最终还是以真机上效果为准
2、输入框是个EditText直接设置背景即可，如我demo的RadiusEditText 可以  editText.getDelegate().setBackgroundColor(Color.WHITE)，设置
