### ISSUE TITLE
关于UIAlertView的对齐

### ISSUE THREAD

**Issue by hegelsu** [AriesHoo/UIWidget#8]
有一个美观上的需求：
UIAlertView能否这样：如果文字只有一行且没有换行的情况下默认是居中显示，只要有换行则默认为左对齐，这样好像更美观些。因为我这里弹出框写成的公用的，消息也为后台返回，但消息很短时居左有点不好看，所以有这样一个建议，请码主考虑下

**Comment by hegelsu** [comment]
补充一下，这里的换行不是给到的字符里有换行，而是指这段字段显示在控件上后如果超过了两行就按上面的处理，因为有可能返回的是一行很长的字符串，字符串里本来没有换行，但因为显示在UIAlertView上后换行了，此时要左对齐，否则居中

**Comment by AriesHoo** [comment]
后面考虑下，最近在完整重构这个项目

**Comment by AriesHoo** [comment]
已重构，参考demo 及jitpack 集成方式  https://jitpack.io/#AriesHoo/UIWidget/3.0.0-alpha1 与之前有不小差异

**Comment by hegelsu** [comment]
最新版处理已看，非常好，谢谢。
